export const NEW_BEER = "NEW_BEER";
export const DELETE_BEER = "DELETE_BEER";
export const UPDATE_BEER = "UPDATE_BEER";
export const INCREASE_BEER_PINT_QUANTITY = "INCREASE_BEER_PINT_QUANTITY";
export const DECREASE_BEER_PINT_QUANTITY = "DECREASE_BEER_PINT_QUANTITY";
export const TOGGLE_EDIT_BEER_FORM_VISIBLE = "TOGGLE_EDIT_FORM_VISIBLE";
export const TOGGLE_NEW_BEER_FORM_VISIBLE = "TOGGLE_NEW_BEER_FORM_VISIBLE";
